spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false

logging:
  level:
    org:
      springframework:
        web: debug
    io.github.cepr0: debug

